language: node_js
node_js:
- '8'
deploy:
  provider: gae
  keyfile: client-secret.json
  project: sam-base
before_install:
- openssl aes-256-cbc -K $encrypted_e88cc985fd8c_key -iv $encrypted_e88cc985fd8c_iv
  -in client-secret.json.enc -out client-secret.json -d
